CONFIG_SYS_PL310_BASE="L2_PL310_BASE"
CONFIG_BOOTM_NETBSD=y
CONFIG_BOARD_EARLY_INIT_F=y
CONFIG_USB_GADGET_DOWNLOAD=y
CONFIG_MXC_USB_FLAGS=0
CONFIG_BOARD_TYPE_POSTFIX=y
CONFIG_IMX_CONFIG="board/fedevel/mx6openrex/mx6q_4x_mt41j256.cfg"
CONFIG_BOOTM_VXWORKS=y
CONFIG_OPENREX_DEFAULT_ARCH_PREFIX=$(CONFIG_BOARD_TYPE_PREFIX)
CONFIG_ENV_DEFAULT_ETH_ADDR="00:0D:15:00:D1:75"
CONFIG_MX6Q=y
CONFIG_SPI_FLASH_SST=y
CONFIG_ARM_ERRATA_751472=y
CONFIG_SF_DEFAULT_MODE="SPI_MODE_0"
CONFIG_SYS_LONGHELP=y
CONFIG_IS_MODULE(option)="config_enabled(CONFIG_VAL(option ##_MODULE))"
CONFIG_DFU_SF=y
CONFIG_SYS_GENERIC_BOARD=y
CONFIG_SYS_LOAD_ADDR=$(CONFIG_LOADADDR)
CONFIG_DISPLAY_BOARDINFO=y
CONFIG_SYS_MEMTEST_SCRATCH=0x10800000
CONFIG_CMD_CACHE=y
CONFIG_STACKSIZE="(128 * 1024)"
CONFIG_BOOTDELAY=3
CONFIG_SYS_SATA_MAX_DEVICE=y
CONFIG_SYS_HELP_CMD_WIDTH=8
CONFIG_NR_DRAM_BANKS=y
CONFIG_FS_FAT=y
CONFIG_BOOTM_RTEMS=y
CONFIG_SYS_CBSIZE=512
CONFIG_DDR_SIZE="SZ_2G"
CONFIG_BOOTM_LINUX=y
CONFIG_BOARD_LATE_INIT=y
CONFIG_CMD_SATA=y
CONFIG_MII=y
CONFIG_CMD_FAT=y
CONFIG_DWC_AHSATA=y
CONFIG_SYS_CACHELINE_SIZE=32
CONFIG_MMC=y
CONFIG_CMD_USB_MASS_STORAGE=y
CONFIG_REVISION_TAG=y
CONFIG_SYS_FSL_SEC_ADDR="CAAM_BASE_ADDR"
CONFIG_PHY_MICREL_KSZ9031=y
CONFIG_ENV_OFFSET="(768 * 1024)"
CONFIG_MXC_OCOTP=y
CONFIG_USB_MAX_CONTROLLER_COUNT=2
CONFIG_ENV_SPI_CS=$(CONFIG_SF_DEFAULT_CS)
CONFIG_ENV_OVERWRITE=y
CONFIG_USB_GADGET_VBUS_DRAW=2
CONFIG_ENV_SIZE="(8 * 1024)"
CONFIG_G_DNL_VENDOR_NUM=0x0525
CONFIG_INITRD_TAG=y
CONFIG_SUPPORT_RAW_INITRD=y
CONFIG_CMD_FS_GENERIC=y
CONFIG_CMD_PING=y
CONFIG_SYS_L2_PL310=y
CONFIG_SYS_MALLOC_LEN="(10 * SZ_1M)"
CONFIG_SYS_I2C_SPEED=100000
CONFIG_SYS_TEXT_BASE=0x17800000
CONFIG_USB_FUNCTION_MASS_STORAGE=y
CONFIG_MXC_GPT_HCLK=y
CONFIG_MXC_UART=y
CONFIG_ENV_SECT_SIZE="(8 * 1024)"
CONFIG_SYS_BARGSIZE=$(CONFIG_SYS_CBSIZE)
CONFIG_BOOTM_PLAN9=y
CONFIG_IS_BUILTIN(option)="config_enabled(CONFIG_VAL(option))"
CONFIG_MXC_USB_PORTSC="(PORT_PTS_UTMI | PORT_PTS_PTW)"
CONFIG_ENV_DEFAULT_CLIENT_IP="192.168.0.150"
CONFIG_ANDROID_BOOT_IMAGE=y
CONFIG_SYS_FSL_JR0_ADDR="(CAAM_BASE_ADDR + 0x1000)"
CONFIG_BOARD_TYPE_PREFIX="imx6q-"
CONFIG_SF_DEFAULT_BUS=2
CONFIG_SYS_MAXARGS=32
CONFIG_SYS_PBSIZE="(CONFIG_SYS_CBSIZE + 128)"
CONFIG_ENV_DEFAULT_FDT_FILE="CONFIG_OPENREX_DEFAULT_ARCH_PREFIX "openrex" CONFIG_OPENREX_DEFAULT_ARCH_POSTFIX ".dtb""
CONFIG_FEC_XCV_TYPE="RGMII"
CONFIG_MXC_GPIO=y
CONFIG_ARM_ERRATA_743622=y
CONFIG_BOARDDIR="board/fedevel/mx6openrex"
CONFIG_EHCI_HCD_INIT_AFTER_RESET=y
CONFIG_BOUNCE_BUFFER=y
CONFIG_OF_LIBFDT=y
CONFIG_PHYLIB=y
CONFIG_BOARD_POSTCLK_INIT=y
CONFIG_CMDLINE_EDITING=y
CONFIG_CMD_USB=y
CONFIG_ENV_DEFAULT_TFTP_DIR="imx6"
CONFIG_CMD_EXT2=y
CONFIG_CMD_EXT4=y
CONFIG_USB_EHCI=y
CONFIG_BOOTCOMMAND="run bootmmc;"
CONFIG_SYS_EXTRA_OPTIONS="IMX_CONFIG=board/fedevel/mx6openrex/mx6q_4x_mt41j256.cfg,MX6Q,DDR_SIZE=SZ_2G,BOARD_TYPE_PREFIX="imx6q-",BOARD_TYPE_POSTFIX="""
CONFIG_CMD_DFU=y
CONFIG_G_DNL_PRODUCT_NUM=0xa4a5
CONFIG_ZLIB=y
CONFIG_LOADADDR=0x12000000
CONFIG_USB_GADGET_DUALSPEED=y
CONFIG_G_DNL_MANUFACTURER="FSL"
CONFIG_ETHPRIME="FEC"
CONFIG_CMD_BOOTZ=y
CONFIG_AUTO_COMPLETE=y
CONFIG_ENV_DEFAULT_SERVER_IP="192.168.0.1"
CONFIG_MP=y
CONFIG_FSL_USDHC=y
CONFIG_ENV_DEFAULT_NFSROOT="/home/fedevel/nfs"
CONFIG_DOS_PARTITION=y
CONFIG_GZIP=y
CONFIG_SATAROOT="/dev/sda2"
CONFIG_USB_FUNCTION_DFU=y
CONFIG_CMD_SF=y
CONFIG_SYS_FSL_ESDHC_ADDR=0
CONFIG_SYS_INIT_RAM_SIZE="IRAM_SIZE"
CONFIG_FEC_MXC_PHYADDR=3
CONFIG_SYS_BAUDRATE_TABLE="{ 9600, 19200, 38400, 57600, 115200 }"
CONFIG_VAL(option)="config_val(option)"
CONFIG_FASTBOOT_BUF_SIZE=0x07000000
CONFIG_SYS_HUSH_PARSER=y
CONFIG_SYS_SDRAM_BASE="PHYS_SDRAM"
CONFIG_IMAGE_FORMAT_LEGACY=y
CONFIG_SYS_BOOT_RAMDISK_HIGH=y
CONFIG_FASTBOOT_BUF_ADDR=$(CONFIG_SYS_LOAD_ADDR)
CONFIG_CMD_DHCP=y
CONFIG_SYS_FSL_USDHC_NUM=y
CONFIG_USB_ETHER_ASIX=y
CONFIG_GENERIC_MMC=y
CONFIG_SYS_INIT_SP_OFFSET="(CONFIG_SYS_INIT_RAM_SIZE - GENERATED_GBL_DATA_SIZE)"
CONFIG_ENV_SPI_MODE=$(CONFIG_SF_DEFAULT_MODE)
CONFIG_ENV_DEFAULT_UBT_FILE="u-boot-" CONFIG_OPENREX_DEFAULT_ARCH_PREFIX "openrex" CONFIG_OPENREX_DEFAULT_ARCH_POSTFIX ".imx"
CONFIG_FAT_WRITE=y
CONFIG_MXC_SPI=y
CONFIG_SYS_I2C=y
CONFIG_SYS_INIT_RAM_ADDR="IRAM_BASE_ADDR"
CONFIG_CI_UDC=y
CONFIG_OPENREX_DEFAULT_ARCH_POSTFIX=$(CONFIG_BOARD_TYPE_POSTFIX)
CONFIG_ENV_SPI_MAX_HZ=$(CONFIG_SF_DEFAULT_SPEED)
CONFIG_EXTRA_ENV_SETTINGS="tftp_dir=" CONFIG_ENV_DEFAULT_TFTP_DIR "0tftp_dir=" CONFIG_ENV_DEFAULT_TFTP_DIR "0script=" CONFIG_ENV_DEFAULT_SCR_FILE "0image=zImage0fdt_file=" CONFIG_ENV_DEFAULT_FDT_FILE "0fdt_addr=0x180000000boot_fdt=try0ip_dyn=yes0nfsroot=" CONFIG_ENV_DEFAULT_NFSROOT "0console=" CONFIG_CONSOLE_DEV "0dfuspi=dfu 0 sf 0:0:10000000:00dfu_alt_info_spl=spl raw 0x4000dfu_alt_info_img=u-boot raw 0x100000dfu_alt_info=spl raw 0x4000fdt_high=0xffffffff0initrd_high=0xffffffff0mmcdev=00mmcpart=10satadev=00satapart=10mmcroot=" CONFIG_MMCROOT " rootwait rw0sataroot=" CONFIG_SATAROOT " rootwait rw0spidev=" __stringify(CONFIG_ENV_SPI_BUS) "0spics=" __stringify(CONFIG_ENV_SPI_CS) "0set_ethernet=if test ${ethaddr}; then; else setenv ethaddr  " CONFIG_ENV_DEFAULT_ETH_ADDR "; fi; if test ${ipaddr}; then; else setenv ipaddr   " CONFIG_ENV_DEFAULT_CLIENT_IP "; fi; if test -n ${serverip}; then; else setenv serverip " CONFIG_ENV_DEFAULT_SERVER_IP "; fi; if test ${netmask}; then; else setenv netmask  " CONFIG_ENV_DEFAULT_NETMASK "; fi0update_set_filename=if test ${upd_uboot}; then; else setenv upd_uboot " CONFIG_ENV_DEFAULT_UBT_FILE "; fi; if test ${upd_kernel}; then; else setenv upd_kernel " CONFIG_ENV_DEFAULT_IMG_FILE "; fi; if test ${upd_fdt}; then; else setenv upd_fdt    " CONFIG_ENV_DEFAULT_FDT_FILE "; fi; if test ${upd_script}; then; else setenv upd_script " CONFIG_ENV_DEFAULT_SCR_FILE "; fi0update_uboot=run set_ethernet; run update_set_filename; if mmc dev ${mmcdev}; then if tftp ${tftp_dir}/${upd_uboot}; then setexpr fw_sz ${filesize} / 0x200; setexpr fw_sz ${fw_sz} + 1; mmc write ${loadaddr} 0x2 ${fw_sz}; fi; fi0update_kernel=run set_ethernet; run update_set_filename; if mmc dev ${mmcdev}; then if tftp ${tftp_dir}/${upd_kernel}; then fatwrite mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image} ${filesize}; fi; fi0update_fdt=run set_ethernet; run update_set_filename; if mmc dev ${mmcdev}; then if tftp ${tftp_dir}/${upd_fdt}; then fatwrite mmc ${mmcdev}:${mmcpart} ${loadaddr} ${fdt_file} ${filesize}; fi; fi0update_spi_uboot=run set_ethernet; run update_set_filename; mw.b ${loadaddr} 0xFF 0x80000; tftp ${tftp_dir}/${upd_uboot}; sf probe;sf erase 0x0 0x80000; sf write ${loadaddr} 0x400 0x80000 0update_script=run set_ethernet; run update_set_filename; if mmc dev ${mmcdev}; then if tftp ${tftp_dir}/${upd_script}; then fatwrite mmc ${mmcdev}:${mmcpart} ${loadaddr} ${script} ${filesize}; fi; fi0update_sd_firmware=if test ${ip_dyn} = yes; then setenv get_cmd dhcp; else setenv get_cmd tftp; fi; if mmc dev ${mmcdev}; then if ${get_cmd} ${update_sd_firmware_filename}; then setexpr fw_sz ${filesize} / 0x200; setexpr fw_sz ${fw_sz} + 1; mmc write ${loadaddr} 0x2 ${fw_sz}; fi; fi0" EMMC_ENV "video_args_hdmi=setenv video_args $video_args video=mxcfb${fb}:dev=hdmi,1280x720M@60,if=RGB240video_args_lvds=setenv video_args $video_args video=mxcfb${fb}:dev=ldb,LDB-XGA,if=RGB6660video_args_lcd=setenv video_args $video_args video=mxcfb${fb}:dev=lcd,CLAA-WVGA,if=RGB6660fb=00video_interfaces=hdmi0video_args_script=for v in ${video_interfaces}; do run video_args_${v}; setexpr fb $fb + 1; done0mmcargs=setenv bootargs console=${console},${baudrate} root=${mmcroot} " VIDEO_ARGS "0sataargs=setenv bootargs console=${console},${baudrate} root=${sataroot} " VIDEO_ARGS "0loadbootscript=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${script};0bootscript=echo Running bootscript from mmc ...; source0loadimage=fatload mmc ${mmcdev}:${mmcpart} ${loadaddr} ${image}0loadfdt=fatload mmc ${mmcdev}:${mmcpart} ${fdt_addr} ${fdt_file}0sataloadimage=fatload sata ${satadev}:${satapart} ${loadaddr} ${image}0sataloadfdt=fatload sata ${satadev}:${satapart} ${fdt_addr} ${fdt_file}0mmcboot=" VIDEO_ARGS_SCRIPT "run mmcargs; if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if run loadfdt; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else bootz; fi;0bootmmc=echo Booting from MMC ...; run findfdt;mmc dev ${mmcdev};if mmc rescan; then if run loadbootscript; then run bootscript; else if run loadimage; then run mmcboot; else run netboot; fi; fi; else run netboot; fi;0bootsata=echo Booting from SATA ...; " VIDEO_ARGS_SCRIPT "run findfdt; run sataargs; if sata init; then if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if run sataloadimage; then if run sataloadfdt; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else echo WARN: Cannot load the image; fi; else bootz; fi; else run netboot; fi;0netargs=setenv bootargs console=${console},${baudrate} root=/dev/nfs ip=dhcp nfsroot=${serverip}:${nfsroot},v3,tcp rootwait rw0netboot=echo Booting from net ...; run set_ethernet; run update_set_filename; run netargs; tftp ${loadaddr} ${tftp_dir}/${upd_kernel}; if test ${boot_fdt} = yes || test ${boot_fdt} = try; then if tftp ${fdt_addr} ${tftp_dir}/${upd_fdt}; then bootz ${loadaddr} - ${fdt_addr}; else if test ${boot_fdt} = try; then bootz; else echo WARN: Cannot load the DT; fi; fi; else bootz; fi;0findfdt=if test $fdt_file = undefined; then if test $board_name = iMX6-OpenRex && test $board_rev = MX6Q; then setenv fdt_file imx6q-openrex.dtb; fi; if test $board_name = iMX6-OpenRex && test $board_rev = MX6DL; then setenv fdt_file imx6dl-openrex.dtb; fi; if test $fdt_file = undefined; then echo WARNING: Could not determine dtb to use; fi; fi;0bootnet=run netboot;0"
CONFIG_CMD_FASTBOOT=y
CONFIG_SYS_INIT_SP_ADDR="(CONFIG_SYS_INIT_RAM_ADDR + CONFIG_SYS_INIT_SP_OFFSET)"
CONFIG_FSL_ESDHC=y
CONFIG_ARM_ERRATA_761320=y
CONFIG_IMX_THERMAL=y
CONFIG_BAUDRATE=115200
CONFIG_CMD_BMODE=y
CONFIG_ENV_IS_IN_SPI_FLASH=y
CONFIG_CMDLINE_TAG=y
CONFIG_ENV_DEFAULT_SCR_FILE="boot-" CONFIG_OPENREX_DEFAULT_ARCH_PREFIX "openrex" CONFIG_OPENREX_DEFAULT_ARCH_POSTFIX ".scr"
CONFIG_MXC_UART_BASE="UART1_BASE"
CONFIG_ARM_ERRATA_794072=y
CONFIG_DFU_MMC=y
CONFIG_USB_HOST_ETHER=y
CONFIG_ENV_DEFAULT_NETMASK="255.255.255.0"
CONFIG_PARTITIONS=y
CONFIG_SYS_MEMTEST_END=0x10010000
CONFIG_CMD_I2C=y
CONFIG_LIBATA=y
CONFIG_FEC_MXC=y
CONFIG_USBD_HS=y
CONFIG_SYS_NO_FLASH=y
CONFIG_SYS_DEF_EEPROM_ADDR=0
CONFIG_ARP_TIMEOUT="200UL"
CONFIG_FS_EXT4=y
CONFIG_DWC_AHSATA_PORT_ID=0
CONFIG_MACH_TYPE=5082
CONFIG_USB_STORAGE=y
CONFIG_USB_EHCI_MX6=y
CONFIG_DISPLAY_CPUINFO=y
CONFIG_MMCROOT="/dev/mmcblk1p2"
CONFIG_SETUP_MEMORY_TAGS=y
CONFIG_EXT4_WRITE=y
CONFIG_SYS_MEMTEST_START=0x10000000
CONFIG_CMD_EXT4_WRITE=y
CONFIG_SF_DEFAULT_SPEED=20000000
CONFIG_CONS_INDEX=y
CONFIG_LMB=y
CONFIG_ENV_SPI_BUS=$(CONFIG_SF_DEFAULT_BUS)
CONFIG_SYS_I2C_MXC=y
CONFIG_PHY_MICREL=y
CONFIG_IS_ENABLED(option)="(config_enabled(CONFIG_VAL(option)) || config_enabled(CONFIG_VAL(option ##_MODULE)))"
CONFIG_DWC_AHSATA_BASE_ADDR="SATA_ARB_BASE_ADDR"
CONFIG_CMD_GPIO=y
CONFIG_ENV_VARS_UBOOT_RUNTIME_CONFIG=y
CONFIG_SYS_I2C_MXC_I2C1=y
CONFIG_SYS_I2C_MXC_I2C2=y
CONFIG_SYS_I2C_MXC_I2C3=y
CONFIG_LBA48=y
CONFIG_USB_FUNCTION_FASTBOOT=y
CONFIG_CMD_MII=y
CONFIG_USB_GADGET=y
CONFIG_SPI_FLASH_SST26=y
CONFIG_CMD_MMC=y
CONFIG_CMD_FUSE=y
CONFIG_ENV_DEFAULT_IMG_FILE=""zImage-" CONFIG_OPENREX_DEFAULT_ARCH_PREFIX "openrex" CONFIG_OPENREX_DEFAULT_ARCH_POSTFIX"
CONFIG_SF_DEFAULT_CS=y
CONFIG_CONSOLE_DEV="ttymxc0"
